spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
      x-forwarded:
        prefixEnabled: true
# GraphQL WS Broker Configuration properties
#  activiti:
#    cloud:
#      services:
#        query:
#          graphql:
#            ws:
#              enabled: ${ACT_GRAPHQL_WS_ENABLED:true}
#              endpoint: ${ACT_GRAPHQL_WS_ENDPOINT:/ws/graphql}
#              allowed-origins: ${ACT_GRAPHQL_WS_ALLOWED_ORIGINS:*}
# having to take security out even from classpath as netty not happy
#              security:
#                enabled: ${ACT_GRAPHQL_WS_SECURITY_ENABLED:false}
#                authorities: ${ACT_GRAPHQL_WS_SECURITY_AUTHORITIES:graphql-ws,admin}
# log level seems to be needed explicitly
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: INFO
server.port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
